# Generated by Django 5.1.3 on 2024-11-10 16:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('carnet de conducir', 'Carnet de Conducir'), ('pasaporte', 'Pasaporte')], max_length=30)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('fecha_expedicion', models.DateField()),
                ('primer_apellido', models.CharField(max_length=255)),
                ('segundo_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('sexo', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, max_length=3000, null=True)),
                ('direccion', models.CharField(max_length=300)),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calificacion', models.DecimalField(decimal_places=1, default=3.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('porcentaje_reserva', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('imagen', models.ImageField(upload_to='img/propiedades/')),
                ('permite_mascotas', models.BooleanField(default=False)),
                ('en_mantenimiento', models.BooleanField(default=False)),
                ('capacidad_maxima', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimplexRentalisAPP.identidades')),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('mascotas', models.BooleanField(default=False)),
                ('tipo_mascota', models.CharField(blank=True, choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], default=None, max_length=10, null=True)),
                ('personas', models.ManyToManyField(related_name='reservas', through='SimplexRentalisAPP.ReservaPersona', to='SimplexRentalisAPP.identidades')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimplexRentalisAPP.propiedades')),
            ],
        ),
        migrations.AddField(
            model_name='reservapersona',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimplexRentalisAPP.reservas'),
        ),
        migrations.AddField(
            model_name='identidades',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimplexRentalisAPP.reservas'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('biografia', models.TextField(blank=True, null=True)),
                ('es_propietario', models.BooleanField(default=False)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='reservas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimplexRentalisAPP.user'),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimplexRentalisAPP.user'),
        ),
        migrations.CreateModel(
            name='Opiniones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimplexRentalisAPP.propiedades')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimplexRentalisAPP.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reservapersona',
            constraint=models.UniqueConstraint(fields=('reserva', 'identidad'), name='unique_reserva_identidad'),
        ),
        migrations.AddIndex(
            model_name='reservas',
            index=models.Index(fields=['propiedad', 'fecha_inicio', 'fecha_fin'], name='SimplexRent_propied_b7dd78_idx'),
        ),
        migrations.AddIndex(
            model_name='reservas',
            index=models.Index(fields=['propiedad'], name='SimplexRent_propied_cc84e2_idx'),
        ),
        migrations.AddIndex(
            model_name='reservas',
            index=models.Index(fields=['usuario'], name='SimplexRent_usuario_927545_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservas',
            constraint=models.UniqueConstraint(fields=('propiedad', 'fecha_inicio', 'fecha_fin'), name='unique_reserva_fecha'),
        ),
        migrations.AddConstraint(
            model_name='propiedades',
            constraint=models.UniqueConstraint(fields=('direccion', 'propietario'), name='unique_direccion_propietario'),
        ),
    ]
