# Generated by Django 5.1.3 on 2024-11-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimplexRentalisAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='biografia',
        ),
    ]
