# Generated by Django 5.1.3 on 2024-11-18 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimplexRentalisAPP', '0004_alter_user_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedades',
            name='imagen',
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='img/propiedades/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('portada', models.BooleanField(default=False)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='SimplexRentalisAPP.propiedades')),
            ],
            options={
                'verbose_name': 'Imagen de la propiedad',
                'verbose_name_plural': 'Galería de imágenes de las propiedades',
            },
        ),
        migrations.AddField(
            model_name='propiedades',
            name='galeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='SimplexRentalisAPP.galeria'),
        ),
    ]
