# Generated by Django 5.1.1 on 2024-10-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimplexRentalisAPP', '0004_remove_imagen_url_imagen_imagen_opinion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
    ]
