# Generated by Django 5.1.3 on 2024-11-21 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimplexRentalisAPP', '0006_alter_galeria_imagen_alter_opiniones_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(upload_to='propiedades/'),
        ),
        migrations.AlterField(
            model_name='opiniones',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
