# Generated by Django 5.1.1 on 2024-10-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimplexRentalisAPP', '0006_usuario_nombre_alter_usuario_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagen',
            new_name='Imagenes',
        ),
        migrations.RenameModel(
            old_name='Opinion',
            new_name='Opiniones',
        ),
        migrations.RenameModel(
            old_name='Propiedad',
            new_name='Propiedades',
        ),
        migrations.RenameModel(
            old_name='Reserva',
            new_name='Reservas',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
    ]
