# Generated by Django 5.1.1 on 2024-10-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimplexRentalisAPP', '0007_rename_imagen_imagenes_rename_opinion_opiniones_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentoIdentidad',
            new_name='DocumentosDeIdentidades',
        ),
    ]
