# Generated by Django 5.1.3 on 2024-11-26 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimplexRentalisAPP', '0009_alter_propiedades_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedades',
            name='galeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades_galeria', to='SimplexRentalisAPP.galeria'),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to=settings.AUTH_USER_MODEL),
        ),
    ]
