# Generated by Django 5.1.3 on 2024-12-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimplexRentalisAPP', '0011_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='codigo_postal',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='numero_casa',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='numero_puerta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
