# Generated by Django 4.2.16 on 2024-12-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimplexRentalisAPP', '0015_propiedades_cantidad_banos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedades',
            name='capacidad_maxima',
            field=models.IntegerField(default=1),
        ),
    ]
