# Generated by Django 4.2.16 on 2024-12-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimplexRentalisAPP', '0016_alter_propiedades_capacidad_maxima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='SimplexRentalisAPP.propiedades'),
        ),
    ]
