# Generated by Django 4.2.16 on 2024-12-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimplexRentalisAPP', '0017_alter_reservas_propiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
