# Generated by Django 4.2.16 on 2024-12-09 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimplexRentalisAPP', '0018_reservas_costo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='identidades',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identidad_asociada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='identidad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_asociado', to='SimplexRentalisAPP.identidades'),
        ),
        migrations.AlterField(
            model_name='identidades',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='identidades',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identidades_reserva', to='SimplexRentalisAPP.reservas'),
        ),
    ]
