# Generated by Django 4.2.16 on 2024-12-12 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimplexRentalisAPP', '0020_reservas_cantidad_personas_alter_identidades_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentidadReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('carnet de conducir', 'Carnet de Conducir'), ('pasaporte', 'Pasaporte')], max_length=30)),
                ('numero_documento', models.CharField(max_length=50)),
                ('fecha_expedicion', models.DateField()),
                ('primer_apellido', models.CharField(max_length=255)),
                ('segundo_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('sexo', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdentidadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('carnet de conducir', 'Carnet de Conducir'), ('pasaporte', 'Pasaporte')], max_length=30)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('fecha_expedicion', models.DateField()),
                ('primer_apellido', models.CharField(max_length=255)),
                ('segundo_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('sexo', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='identidad',
        ),
        migrations.AddField(
            model_name='user',
            name='identidad_usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_asociado', to='SimplexRentalisAPP.identidadusuario'),
        ),
        migrations.AlterField(
            model_name='reservapersona',
            name='identidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimplexRentalisAPP.identidadreserva'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='personas',
            field=models.ManyToManyField(related_name='reservas', through='SimplexRentalisAPP.ReservaPersona', to='SimplexRentalisAPP.identidadreserva'),
        ),
        migrations.DeleteModel(
            name='Identidades',
        ),
    ]
