# Generated by Django 4.2.16 on 2024-12-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimplexRentalisAPP', '0023_opinionvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinionvote',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='opinionvote',
            unique_together={('opinion', 'usuario')},
        ),
        migrations.AddField(
            model_name='opinionvote',
            name='voto',
            field=models.CharField(choices=[('like', 'Me gusta'), ('dislike', 'No me gusta')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='opinionvote',
            name='vote',
        ),
    ]
