# Generated by Django 4.2.16 on 2025-02-01 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimplexRentalisAPP', '0024_rename_user_opinionvote_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcciones',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='SimplexRentalisAPP.direcciones'),
        ),
    ]
