Habrá un solo tipo de usuario en el sistema. Todos los usuarios podrán ser tanto **viajeros** como **propietarios**, dependiendo de si tienen o no propiedades registradas a su nombre. El sistema detectará automáticamente el rol según ciertas condiciones. Un **viajero** es un usuario que no tiene ninguna propiedad registrada en su cuenta. Estos viajeros podrán contratar servicios de alquiler, buscar y reservar propiedades, pero no tendrán acceso a las funcionalidades de gestión de propiedades. Por otro lado, un **propietario** es un usuario que tiene al menos una propiedad registrada en su cuenta. Además de poder contratar servicios de alquiler como cualquier viajero, el sistema habilitará las opciones de gestión de propiedades, permitiéndoles registrar, actualizar y eliminar sus propiedades.

Los usuarios contarán con varios atributos que el sistema gestionará para definir su rol y permitir diversas funcionalidades. El **ID de usuario** servirá como identificador único del usuario, mientras que las **propiedades registradas** se utilizarán para determinar si el usuario se comporta como viajero o propietario: si este campo está vacío, el usuario se comporta como un viajero; si tiene propiedades, podrá acceder a las funcionalidades de propietario. La **dirección de correo electrónico** asociada a la cuenta se usará para el inicio de sesión, recuperación de cuenta y notificaciones. Asimismo, la **contraseña** será una cadena encriptada que el usuario utilizará para acceder a su cuenta. Por último, la **fecha de creación** registrará la fecha y hora en que se creó la cuenta del usuario.

Un usuario inicialmente se comportará como un viajero hasta que registre su primera propiedad. Una vez que lo haga, el sistema automáticamente le permitirá acceder a las funcionalidades de un propietario. Si un propietario elimina todas sus propiedades, el sistema cambiará automáticamente su comportamiento para que vuelva a ser un viajero.

Las propiedades podrán tener un único dueño, pero ese dueño podrá tener más propiedades. Cada propiedad tendrá un campo al que llamaremos **título**, que recogerá el nombre de la casa. Se necesita asignar una dirección del hogar y una descripción sobre la propiedad. Es importante tener en cuenta que las propiedades serán medidas según un sistema de estrellas que irá de 0 a 5, basado en las opiniones de los viajeros. Estas opiniones serán completamente opcionales y solo podrán ser realizadas por aquellos que hayan alquilado la estancia y cuya estancia haya concluido. No será necesario asignar un comentario para dar una puntuación, pero será posible hacerlo. Sin embargo, un solo viajero podrá asignar una sola puntuación y un solo comentario a ese hogar.

Los comentarios podrán incluir imágenes que irán de 0 a 5, por si los viajeros necesitan relatar su experiencia con imágenes, aunque no serán obligatorias. Cada propiedad deberá tener al menos 5 imágenes, siendo una de ellas obligatoriamente la imagen de portada del hogar, la cual deberá mostrar el exterior de la propiedad. El número máximo de imágenes permitidas será de 15.

Cada propiedad tendrá un **precio** registrado, que puede variar con el tiempo, así como un porcentaje a abonar por la reserva. Los propietarios tendrán acceso a un apartado para gestionar sus reservas, donde podrán visualizar cuándo tienen alquiladas sus propiedades de forma individual. Se recogerá el tiempo de duración del alquiler de la estancia (entrada y salida), el precio por noche, y el dinero ofrecido por el viajero para reservar la propiedad, que será un porcentaje indicado por cada propietario para cada una de sus propiedades. Este dinero se restará del total del coste de la estancia y se registrará también qué usuarios viajeros han alquilado.

Es importante aclarar que el viajero puede cancelar su reserva, ya que para alquilar una propiedad debe pagar en el momento de la reserva el dinero correspondiente por la misma. Además, al registrar una reserva, el usuario deberá indicar la cantidad de viajeros que le acompañan, diferenciando entre niños y adultos, y si tiene mascota, indicando el tipo (perro, gato, otro).

El viajero que alquila la propiedad deberá ser mayor de edad y cada acompañante de 16 años o más deberá presentar junto a él los siguientes datos, cada uno de forma individual: tipo de documento de identificación (podrá elegir entre DNI, carnet de conducir y pasaporte), número de documento de identidad, fecha de expedición del documento, primer apellido, segundo apellido, nombre, sexo, fecha de nacimiento, país de nacionalidad y fecha de entrada a la propiedad alquilada. La fecha de expedición no puede ser inferior a la fecha de nacimiento, y no puede haber dos o más personas registradas con el mismo DNI, carnet de conducir o pasaporte.
