# Generated by Django 5.1.1 on 2024-10-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimplexRentalisAPP', '0003_propiedad_usuario_remove_booking_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='url',
        ),
        migrations.AddField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(default='images/default_image.jpg', upload_to='imagenes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='opiniones/'),
        ),
    ]
