# Generated by Django 5.1.3 on 2024-11-09 18:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlquilerAPP', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='propiedades',
            name='en_mantenimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='imagen',
            field=models.ImageField(default='img/propiedades/default_image.jpg', upload_to='img/propiedades/'),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='permite_mascotas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='porcentaje_reserva',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='reservas',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservas',
            name='mascotas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas',
            name='tipo_mascota',
            field=models.CharField(blank=True, choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identidades',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='opiniones',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='opiniones',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='descripcion',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='propiedades',
            constraint=models.UniqueConstraint(fields=('direccion', 'propietario'), name='unique_direccion_propietario'),
        ),
        migrations.AddField(
            model_name='reservapersona',
            name='identidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlquilerAPP.identidades'),
        ),
        migrations.AddField(
            model_name='reservapersona',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlquilerAPP.reservas'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='personas',
            field=models.ManyToManyField(related_name='reservas', through='AlquilerAPP.ReservaPersona', to='AlquilerAPP.identidades'),
        ),
        migrations.AddIndex(
            model_name='reservas',
            index=models.Index(fields=['propiedad', 'fecha_inicio', 'fecha_fin'], name='AlquilerAPP_propied_e87f42_idx'),
        ),
        migrations.AddIndex(
            model_name='reservas',
            index=models.Index(fields=['propiedad'], name='AlquilerAPP_propied_73c838_idx'),
        ),
        migrations.AddIndex(
            model_name='reservas',
            index=models.Index(fields=['usuario'], name='AlquilerAPP_usuario_b8f98c_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservas',
            constraint=models.UniqueConstraint(fields=('propiedad', 'fecha_inicio', 'fecha_fin'), name='unique_reserva_fecha'),
        ),
        migrations.AddConstraint(
            model_name='reservapersona',
            constraint=models.UniqueConstraint(fields=('reserva', 'identidad'), name='unique_reserva_identidad'),
        ),
    ]
